# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Stylesheets
stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css

# Scripts
scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js
  - /js/daoloth.js